const constant = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_CLEAR: 'AUTH_CLEAR',
  GET_PROFILE: 'GET_PROFILE',
  GET_USERS: 'GET_USERS',
  GET_DETAIL_USER: 'GET_DETAIL_USER',
  GET_HOBBIES: 'GET_HOBBIES',
  EDIT_USER_HOBBY: 'EDIT_USER_HOBBY',
  GET_HOBBY_NAME: 'GET_HOBBY_NAME',
  ADD_HOBBY: 'ADD_HOBBY'

}

export default constant
